import numpy as np

K_OUTER = 5
K_INNER = 3
RANDOM_STATE = 42
SPLITS_OUTPUT_DIR = "cv_splits"

# CoxPHSurvivalAnalysis `alpha` is an L2-regularization strength; it is not
# constrained to [0, 1]. We search a log-scale grid.
_COXPH_ALPHA_GRID = list(10.0 ** np.linspace(-1, 3, 30))
_COXPH_UNIQUE_ALPHAS = sorted(
    {float(np.round(alpha, 3)) for alpha in _COXPH_ALPHA_GRID}, reverse=True
)
COXPH_ALPHAS = _COXPH_UNIQUE_ALPHAS
COXPH_CONFIGS = [
    {
        "name": f"alpha-{alpha:g}",
        "alpha": alpha,
        "internal_ranking": rank,
    }
    for rank, alpha in enumerate(_COXPH_UNIQUE_ALPHAS, start=1)
]

MODEL_CONFIGS = {
    "dryrun": [
        {
            "name": "dryrun-simple",
            "seed": RANDOM_STATE,
            "internal_ranking": 1,
        },
        {
            "name": "dryrun-complex",
            "seed": RANDOM_STATE,
            "internal_ranking": 2,
        },
    ],
    "deepsurv": [
        {
            "name": "ds-lite-64-strongreg",
            "hidden_sizes": [64],
            "dropout": 0.4,
            "lr": 2e-4,
            "weight_decay": 1e-3,
            "batch_size": 256,
            "num_epochs": 200,
            "seed": RANDOM_STATE,
            "internal_ranking": 1,
        },
        {
            "name": "ds-lite-64-weakreg",
            "hidden_sizes": [64],
            "dropout": 0.2,
            "lr": 2e-4,
            "weight_decay": 5e-4,
            "batch_size": 256,
            "num_epochs": 200,
            "seed": RANDOM_STATE,
            "internal_ranking": 2,
        },
        {
            "name": "ds-base-128-strongreg",
            "hidden_sizes": [128],
            "dropout": 0.4,
            "lr": 3e-4,
            "weight_decay": 1e-3,
            "batch_size": 256,
            "num_epochs": 200,
            "seed": RANDOM_STATE,
            "internal_ranking": 3,
        },
        {
            "name": "ds-base-128-weakreg",
            "hidden_sizes": [128],
            "dropout": 0.2,
            "lr": 3e-4,
            "weight_decay": 5e-4,
            "batch_size": 256,
            "num_epochs": 200,
            "seed": RANDOM_STATE,
            "internal_ranking": 4,
        },
        {
            "name": "ds-mlp-128x32-strongreg",
            "hidden_sizes": [128, 32],
            "dropout": 0.4,
            "lr": 5e-4,
            "weight_decay": 1e-3,
            "batch_size": 256,
            "num_epochs": 200,
            "seed": RANDOM_STATE,
            "internal_ranking": 5,
        },
    ],
    "deephit": [
        {
            "name": "dh104-base-strongreg",
            "lr": 2e-4,
            "weight_decay": 1e-3,
            "batch_size": 256,
            "alpha": 0.5,
            "hidden_dims": [128],
            "dropout": 0.4,
            "seed": RANDOM_STATE,
            "num_time_steps": 104,
            "num_epochs": 200,
            "internal_ranking": 1,
        },
        {
            "name": "dh104-base-weakreg",
            "lr": 2e-4,
            "weight_decay": 5e-4,
            "batch_size": 256,
            "alpha": 0.5,
            "hidden_dims": [128],
            "dropout": 0.2,
            "seed": RANDOM_STATE,
            "num_time_steps": 104,
            "num_epochs": 200,
            "internal_ranking": 2,
        },
        {
            "name": "dh104-mid-strongreg",
            "lr": 5e-4,
            "weight_decay": 1e-3,
            "batch_size": 256,
            "alpha": 0.5,
            "hidden_dims": [64, 32],
            "dropout": 0.4,
            "seed": RANDOM_STATE,
            "num_time_steps": 104,
            "num_epochs": 200,
            "internal_ranking": 3,
        },
        {
            "name": "dh104-mid-weakreg",
            "lr": 5e-4,
            "weight_decay": 5e-4,
            "batch_size": 256,
            "alpha": 0.5,
            "hidden_dims": [64, 32],
            "dropout": 0.2,
            "seed": RANDOM_STATE,
            "num_time_steps": 104,
            "num_epochs": 200,
            "internal_ranking": 4,
        },
        {
            "name": "dh196-large-strongreg",
            "lr": 2e-4,
            "weight_decay": 1e-3,
            "batch_size": 256,
            "alpha": 0.5,
            "hidden_dims": [128, 64],
            "dropout": 0.4,
            "seed": RANDOM_STATE,
            "num_time_steps": 196,
            "num_epochs": 200,
            "internal_ranking": 5,
        },
    ],
    "gbsa": [
        # 3x (400): simple, mid, large
        {
            "name": "gbsa-simple-400",
            "n_estimators": 400,
            "learning_rate": 0.05,
            "max_depth": 2,
            "min_samples_split": 10,
            "min_samples_leaf": 50,
            "subsample": 0.5,
            "max_features": 0.3,
            "random_state": RANDOM_STATE,
            "internal_ranking": 1,
        },
        {
            "name": "gbsa-mid-400",
            "n_estimators": 400,
            "learning_rate": 0.05,
            "max_depth": 3,
            "min_samples_split": 10,
            "min_samples_leaf": 50,
            "subsample": 0.7,
            "max_features": 0.3,
            "random_state": RANDOM_STATE,
            "internal_ranking": 2,
        },
        {
            "name": "gbsa-large-400",
            "n_estimators": 400,
            "learning_rate": 0.05,
            "max_depth": 3,
            "min_samples_split": 10,
            "min_samples_leaf": 5,
            "subsample": 1.0,
            "max_features": 0.5,
            "random_state": RANDOM_STATE,
            "internal_ranking": 3,
        },
        {
            "name": "gbsa-simple-800",
            "n_estimators": 800,
            "learning_rate": 0.05,
            "max_depth": 2,
            "min_samples_split": 10,
            "min_samples_leaf": 50,
            "subsample": 0.5,
            "max_features": 0.3,
            "random_state": RANDOM_STATE,
            "internal_ranking": 4,
        },
        {
            "name": "gbsa-mid-800",
            "n_estimators": 800,
            "learning_rate": 0.05,
            "max_depth": 3,
            "min_samples_split": 10,
            "min_samples_leaf": 50,
            "subsample": 0.7,
            "max_features": 0.3,
            "random_state": RANDOM_STATE,
            "internal_ranking": 5,
        },
    ],
    "rsf": [
        {
            "name": "rsf-simple-400",
            "n_estimators": 400,
            "max_depth": None,
            "min_samples_split": 10,
            "min_samples_leaf": 50,
            "max_features": 0.3,
            "bootstrap": True,
            "n_jobs": -1,
            "random_state": RANDOM_STATE,
            "internal_ranking": 1,
        },
        {
            "name": "rsf-mid-400",
            "n_estimators": 400,
            "max_depth": None,
            "min_samples_split": 10,
            "min_samples_leaf": 20,
            "max_features": 0.3,
            "bootstrap": True,
            "n_jobs": -1,
            "random_state": RANDOM_STATE,
            "internal_ranking": 3,
        },
        {
            "name": "rsf-large-400",
            "n_estimators": 400,
            "max_depth": None,
            "min_samples_split": 10,
            "min_samples_leaf": 5,
            "max_features": 0.5,
            "bootstrap": True,
            "n_jobs": -1,
            "random_state": RANDOM_STATE,
            "internal_ranking": 5,
        },
        {
            "name": "rsf-simple-800",
            "n_estimators": 800,
            "max_depth": None,
            "min_samples_split": 10,
            "min_samples_leaf": 50,
            "max_features": 0.3,
            "bootstrap": True,
            "n_jobs": -1,
            "random_state": RANDOM_STATE,
            "internal_ranking": 2,
        },
        {
            "name": "rsf-mid-800",
            "n_estimators": 800,
            "max_depth": None,
            "min_samples_split": 10,
            "min_samples_leaf": 20,
            "max_features": 0.3,
            "bootstrap": True,
            "n_jobs": -1,
            "random_state": RANDOM_STATE,
            "internal_ranking": 4,
        },
    ],
    "coxph": COXPH_CONFIGS,
}
